### ISSUE TITLE
yaml checker problem

### ISSUE THREAD

**Issue by roblanf** [roblanf/BenchmarkAlignments#20]
Hey @snubian, 

I've been trying to run the YAML checker. 

On the 'tereza' branch, I do this:

```
source("~/Documents/github/PartitionedAlignments/R/check_yaml/config_yaml.R", chdir = TRUE)
checkYAML("~/Documents/github/PartitionedAlignments/datasets/Anderson_2013")
```

I get this:

```
Error in getClass(Class, where = topenv(parent.frame())) : 
  “SilentReporter” is not a defined class 
```

It _looks like_ I can fix this by changing this (line 29 of config_YAML):

```
reporter = new("SilentReporter")
```

To this 

```
reporter = SilentReporter
```

But I don't really know for sure I'm not doing something terrible. Could you check? 

Unrelated issue - we might have changed our YAML format a touch. Once this is sorted I'll get on to seeing if I can address that...

**Comment by snubian** [comment]
Hey Rob, I'm currently on a train and probably won't get a chance to look at this today - or til later at least. That error looks familiar but I'll need to sit down and look at it ... I wouldn't think you'd need to add the line of code you mentioned though. If u can hang tight I'll check it out asap.
Stu

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Jun 2, 2016 at 5:03 PM -0700, "roblanf" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @snubian<https://github.com/snubian>,

I've been trying to run the YAML checker.

On the 'tereza' branch, I do this:

source("~/Documents/github/PartitionedAlignments/R/check_yaml/config_yaml.R", chdir = TRUE)
checkYAML("~/Documents/github/PartitionedAlignments/datasets/Anderson_2013")


I get this:

Error in getClass(Class, where = topenv(parent.frame())) :
  "SilentReporter" is not a defined class


It looks like I can fix this by changing this (line 29 of config_YAML):

reporter = new("SilentReporter")


To this

reporter = SilentReporter


But I don't really know for sure I'm not doing something terrible. Could you check?

Unrelated issue - we might have changed our YAML format a touch. Once this is sorted I'll get on to seeing if I can address that...

-

**Comment by roblanf** [comment]
totally no rush. I might end up shifting to Python in any case, because it turns out the alignment stuff is already implemented in Python but not R. So probably best to just ignore me for a while...

**Comment by snubian** [comment]
Actually feel free to change it if it gets you out of trouble, can always revert if needed. It's surely not super harmful to do so

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Jun 2, 2016 at 5:03 PM -0700, "roblanf" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @snubian<https://github.com/snubian>,

I've been trying to run the YAML checker.

On the 'tereza' branch, I do this:

source("~/Documents/github/PartitionedAlignments/R/check_yaml/config_yaml.R", chdir = TRUE)
checkYAML("~/Documents/github/PartitionedAlignments/datasets/Anderson_2013")


I get this:

Error in getClass(Class, where = topenv(parent.frame())) :
  "SilentReporter" is not a defined class


It looks like I can fix this by changing this (line 29 of config_YAML):

reporter = new("SilentReporter")


To this

reporter = SilentReporter


But I don't really know for sure I'm not doing something terrible. Could you check?

Unrelated issue - we might have changed our YAML format a touch. Once this is sorted I'll get on to seeing if I can address that...

-

**Comment by snubian** [comment]
Ah coolio.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Jun 2, 2016 at 6:10 PM -0700, "roblanf" <notifications@github.com<mailto:notifications@github.com>> wrote:


totally no rush. I might end up shifting to Python in any case, because it turns out the alignment stuff is already implemented in Python but not R. So probably best to just ignore me for a while...

-

**Comment by roblanf** [comment]
now moved to python
