### ISSUE TITLE
run tests with nextflow

### ISSUE THREAD

**Issue by roblanf** [roblanf/BenchmarkAlignments#41]
Maybe better than just using a python script is to actually manage things properly with a workflow language.

**Comment by roblanf** [comment]
Or a python testing library

**Comment by roblanf** [comment]
@brettc what's your favourite python testing library?

**Comment by brettc** [comment]
pytest is the way to go.

**Comment by roblanf** [comment]
@huaiyanren here's the github issue

**Comment by roblanf** [comment]
The idea is to update all the file checking so that it uses pytest.

**Comment by roblanf** [comment]
done. New tests use pytest
